### ISSUE TITLE
How do i set up something like this for bracket users

### ISSUE THREAD

**Issue by Oluwasetemi** [marcobiedermann/sublime-head-snippets#2]

**Comment by marcobiedermann** [comment]
@Oluwasetemi I've already planned to create a Brackets plugin. Maybe I can tackle this next week

**Comment by marcobiedermann** [comment]
@Oluwasetemi I've just taken a look at how to create a snippet for Brackets. It does look like that you would need a third party extension called "brackets-snippets" (https://github.com/chuyik/brackets-snippets). This does work but unfortunately it writes all snippets into Brackets global config.
I've also seen that you could write an extension instead of a snippets library (https://github.com/codeomnitrix/bootstrap-snippets/blob/master/main.js). If this is the real way how to create snippets in Brackets, I will not create one.
Do you have any experience with creating your own Brackets snippets?

**Comment by Oluwasetemi** [comment]
@marcobiedermann Yes I can create Brackets snippets.

**Comment by Oluwasetemi** [comment]
@marcobiedermann i could create the head snippet and send a pull request to [bracket-snippets](https://github.com/chuyik/brackets-snippets). Or What do you think?
Also writing an extension or snippets library which is preferable?

**Comment by Oluwasetemi** [comment]
![image](https://cloud.githubusercontent.com/assets/10030028/16359802/808155b8-3b3b-11e6-8997-b6ef42e7d473.png)

I added the snippet locally on my bracket.Thanks for your work @marcobiedermann

**Comment by marcobiedermann** [comment]
@Oluwasetemi You are welcome. I will close this for now. If any one else is going to create a brackets plugin, feel free to ping me and I link it in the description.
